from .Video_Batch_Loader import NODE_CLASS_MAPPINGS as VIDEO_BATCH_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as VIDEO_BATCH_DISPLAY
from .Video_Combiner import NODE_CLASS_MAPPINGS as VIDEO_COMBINE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as VIDEO_COMBINE_DISPLAY
from .Prompt_Preset import NODE_CLASS_MAPPINGS as PROMPT_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as PROMPT_DISPLAY

# 合并所有节点映射
NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(VIDEO_BATCH_MAPPINGS)
NODE_CLASS_MAPPINGS.update(VIDEO_COMBINE_MAPPINGS)
NODE_CLASS_MAPPINGS.update(PROMPT_MAPPINGS)

# 合并所有显示名称映射
NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(VIDEO_BATCH_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(VIDEO_COMBINE_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(PROMPT_DISPLAY)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']